[build]
  publish = "public" # This should already match your Netlify settings
  functions = "netlify/functions" # This should already match your Netlify settings

[functions]
  # Tell Netlify to include the serviceAccountKey.json file when bundling functions
  # The path is relative to the repository root.
  included_files = ["./netlify/serviceAccountKey.json"]
